--2025-03-04
-- 아직 푸는 중

SELECT CAR_ID
     ,AVG(datediff(START_DATE, END_DATE) + 1)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(datediff(START_DATE, END_DATE) + 1) >= 7
ORDER BY 2 DESC