--2025-03-09
SELECT CAR_ID
--DATEDIFF('2023-02-14', '2023-02-14')는 값이 0이 나오기 때문에
--시작한 날짜부터 대여일로 계산해야 하는 경우에는 1을 더해줘야 합니다.
, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY 2 DESC, CAR_ID DESC
]