--2025-03-09
SELECT CAR_ID
, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY 2 DESC, CAR_ID DESC

-- 안 풀려서 정답 봤는데,, 왜 ROUND를 써야 결과 조회가 되는 거지이ㅣ