-- 2025-05-06
SELECT  C.SCORE
     ,B.EMP_NO
     ,B.EMP_NAME
     ,B.POSITION
     ,B.EMAIL
FROM HR_DEPARTMENT A INNER JOIN HR_EMPLOYEES B
ON A.DEPT_ID = B.DEPT_ID
INNER JOIN HR_GRADE C
ON B.EMP_NO = C.EMP_NO