--2025-07-25
SELECT  ROUTE
     ,CONCAT(ROUND(COUNT(D_BETWEEN_DIST), 2), 'km') AS TOTAL_DISTANCE
     ,ROUND(AVG(D_CUMULATIVE), 3) AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY 1 DESC