-- 2025-05-09
-- 결과는 나오는데 지저분한 느낌
SELECT (SELECT SUM(SCORE)
        FROM HR_GRADE
        GROUP BY EMP_NO
        ORDER BY 1 DESC
           LIMIT 1) AS SCORE
     ,B.EMP_NO
     ,B.EMP_NAME
     ,B.POSITION
     ,B.EMAIL
FROM HR_DEPARTMENT A INNER JOIN HR_EMPLOYEES B
ON A.DEPT_ID = B.DEPT_ID
    INNER JOIN HR_GRADE C
    ON B.EMP_NO = C.EMP_NO
WHERE B.EMP_NO = (
    SELECT EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY 1 DESC
    LIMIT 1
    )
GROUP BY B.EMP_NO;

SELECT SUM(SCORE)
FROM HR_GRADE
GROUP BY EMP_NO;

SELECT
    CASE WHEN HALF_YEAR = '1' THEN MAX(SCORE)
         WHEN HALF_YEAR = '2' THEN MAX(SCORE)
        END AS SCORE
FROM HR_GRADE
GROUP BY SCORE
ORDER BY 1 DESC