--2024-01-11
SELECT COUNT(B.FISH_NAME) AS FISH_COUNT, B.FISH_NAME
FROM FISH_INFO A JOIN FISH_NAME_INFO B
USING (FISH_TYPE)
GROUP BY B.FISH_NAME
ORDER BY 1 DESC

--using 첫 사용,, 개념을 모르진 않았는데 습관적으로 ON만 사용했당