-- month 사용
SELECT COUNT(*) AS FISH_COUNT, month(time) AS MONTH
FROM FISH_INFO
GROUP BY MONTH
order by MONTH


-- 2025-05-26
SELECT  COUNT(FISH_TYPE) AS FISH_COUNT
        , REPLACE(DATE_FORMAT(TIME, '%m'), '0', '') * 1 AS MONTH
FROM FISH_INFO
GROUP BY REPLACE(DATE_FORMAT(TIME, '%m'), '0', '') * 1
ORDER BY 2