-- 2025-05-25
SELECT  COUNT(FISH_TYPE) AS FISH_COUNT
        , REPLACE(DATE_FORMAT(TIME, '%m'), '0', '') * 1 AS MONTH
FROM FISH_INFO
GROUP BY REPLACE(DATE_FORMAT(TIME, '%m'), '0', '') * 1
ORDER BY REPLACE(DATE_FORMAT(TIME, '%m'), '0', '') * 1