--2025-03-24
SELECT   YEAR(A.DIFFERENTIATION_DATE) AS YEAR
        ,A.SIZE_OF_COLONY
        ,CASE
    WHEN DATE_FORMAT(A.DIFFERENTIATION_DATE, '%Y') = '2019' THEN A.ID END 힝
FROM ECOLI_DATA A LEFT OUTER JOIN (SELECT  MAX(SIZE_OF_COLONY) AS MAX_SIZE
                                          ,DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR
                                   FROM ECOLI_DATA A
                                   GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE, '%Y')) B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR

-- DATE_FORMAT -> YEAR 로 변경