-- 2024-01-08
SELECT TRIM(LEADING '0' FROM DATE_FORMAT(DATETIME, '%H')) AS HOUR
, COUNT(DATE_FORMAT(DATETIME, '%H')) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%h') >= 9
AND DATE_FORMAT(DATETIME, '%H') <= 19
GROUP BY HOUR
ORDER BY DATE_FORMAT(DATETIME, '%H')
-- 이게 내 쿼리고

-- 아래가 다른 사람 쿼리인데 AS 없이 별칭 쓸 수 있는 걸 이제야 알아버렸당.. 와.. ㅠㅠ
-- 형식이 09로 나와야하는 줄 알고 내 쿼리 보면 TRIM 까지 썼다.. 바보얌
-- 아래 쿼리 간결하고 좋아보여서 퍼왔다! 나 쿼리 짠 거 보면 진짜 갈 길이 멀다,,
SELECT DATE_FORMAT(DATETIME, '%H') HOUR,
COUNT(ANIMAL_ID) COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') BETWEEN 09 AND 19
GROUP BY 1
ORDER BY 1