--2024-12-16
-- 다 풀어놓고 오타있어서.. 바보같이ㅣ 못풀고 있었다 ㅠㅠ
-- lv 4
SELECT DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d') AS SALES_DATE
, A.PRODUCT_ID
, A.USER_ID
, A.SALES_AMOUNT
FROM ONLINE_SALE A
WHERE DATE_FORMAT(A.SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL

SELECT DATE_FORMAT(B.SALES_DATE, '%Y-%m-%d') AS SALES_DATE
, B.PRODUCT_ID
, null
, B.SALES_AMOUNT
FROM OFFLINE_SALE B
WHERE DATE_FORMAT(B.SALES_DATE, '%Y-%m') = '2022-03'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID