--2025-03-11
SELECT CAR_TYPE, COUNT(CAR_ID) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%'
   OR OPTIONS LIKE '%열선시트%'
   OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE

-- 아래가 약 5-6개월 전에 풀었던 건데
-- 진짜 바보.. WHERE보다 GROUP BY를 먼저 써서 틀렸어
-- 다시 보고 응? 맞는데 하고.. 순서 바꾸니까 정답이넹

--2024-10-23
SELECT CAR_TYPE, COUNT(CAR_ID) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
GROUP BY CAR_TYPE
    WHERE OPTIONS LIKE '%통풍시트%'
OR OPTIONS LIKE '%열선시트%'
OR OPTIONS LIKE '%가죽시트%'
ORDER BY CAR_TYPE

