--2024-12-23
-- 헉 바보같이 잘 안 풀려서 ,, 다른 사람 쿼리 중에 좋은 거 찾아서 따라했습니당,,
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN(
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 2 DESC
