-- 2025-05-02
SELECT DATE_FORMAT(B.SALES_DATE, '%Y') YEAR
     , DATE_FORMAT(B.SALES_DATE, '%m') MONTH
     , A.GENDER
     , COUNT(DISTINCT A.USER_ID) USERS
    -- 같은 달에 여러 번 구매한 회원이 존재
FROM USER_INFO A INNER JOIN ONLINE_SALE B
                            ON(A.USER_ID = B.USER_ID)
WHERE A.GENDER IS NOT NULL
GROUP BY  DATE_FORMAT(B.SALES_DATE, '%Y')
       , DATE_FORMAT(B.SALES_DATE, '%m')
       , A.GENDER
ORDER BY 1,2,3

--2025-03-27
SELECT DATE_FORMAT(B.SALES_DATE, '%Y') YEAR
, DATE_FORMAT(B.SALES_DATE, '%m') MONTH
     , A.GENDER
     , A.USER_ID USERS
FROM USER_INFO A INNER JOIN ONLINE_SALE B
ON(A.USER_ID = B.USER_ID)
WHERE A.GENDER IS NOT NULL
GROUP BY  DATE_FORMAT(B.SALES_DATE, '%Y')
        , DATE_FORMAT(B.SALES_DATE, '%m')
        , A.GENDER
ORDER BY 1,2,3