--2024-12-10
SELECT DATE_FORMAT(A.SALES_DATE, '%Y-%m-%y') AS SALES_DATE
, A.PRODUCT_ID
, A.USER_ID
, A.SALES_AMOUNT
FROM ONLINE_SALE A
WHERE DATE_FORMAT(A.SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL

SELECT DATE_FORMAT(B.SALES_DATE, '%Y-%m-%y') AS SALES_DATE
, B.PRODUCT_ID
, null
, B.SALES_AMOUNT
FROM OFFLINE_SALE B
WHERE DATE_FORMAT(B.SALES_DATE, '%Y-%m') = '2022-03'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID