--2025-10-16


--2025-10-10
SELECT MEMBER_NAME, REVIEW_TEXT,	REVIEW_DATE
FROM MEMBER_PROFILE A JOIN (
    SELECT MEMBER_ID, REVIEW_TEXT,	REVIEW_DATE
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 1 DESC
        LIMIT 1
) B
                           ON (A.MEMBER_ID = B.MEMBER_ID)



SELECT BOARD_ID
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC
    LIMIT 1
--2025-10-03
SELECT COUNT(MEMBER_ID), MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID

-- 2024-12-26
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (
                        SELECT MEMBER_ID
                        FROM REST_REVIEW
                        GROUP BY MEMBER_ID
                        HAVING MAX(COUNT(*))
                    )
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT