-- 2025-06-10
SELECT   B.EMP_NO
        ,B.EMP_NAME
        ,C.HALF_YEAR
        ,C.SCORE
FROM HR_DEPARTMENT A INNER JOIN HR_EMPLOYEES B
ON A.DEPT_ID = B.DEPT_ID
INNER JOIN HR_GRADE C
ON B.EMP_NO = C.EMP_NO