-- 2024-11-28
SELECT NAME, DATETIME
FROM ANIMAL_INS A
WHERE NOT EXISTS (SELECT 1
     FROM ANIMAL_OUTS B
     WHERE A.ANIMAL_ID = B.ANIMAL_ID)
ORDER BY DATETIME, DATETIME DESC LIMIT 3;

--지렸당 ㅋ 나 짱 빨리 풀었다ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ