--2025-06-05
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
UNION ALL
SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
    )
SELECT HOURS.HOUR
FROM HOURS;






SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR
      ,IFNULL(COUNT(DATE_FORMAT(DATETIME, '%H')), 0) AS COUNT
FROM ANIMAL_OUTS
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY 1
--with절로 일단 시간 먼저 다 조회한 후에 해야하나보당


--2025-04-01
-- 오늘 내 생일
SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR
      ,COUNT(DATE_FORMAT(DATETIME, '%H')) AS COUNT
FROM ANIMAL_OUTS
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY 1

-- https://school.programmers.co.kr/questions/84119
-- 정답은 아님미다