--2025-09-11
SELECT DATE_FORMAT(A.SALES_DATE, '%Y') AS YEAR
,MONTH	PURCHASED_USERS	PUCHASED_RATIO
FROM USER_INFO A INNER JOIN ONLINE_SALE B
ON (A.USER_ID = B.USER_ID)
WHERE DATE_FORMAT(A.JOINED, '%Y') = '2021'

-- 2025-08-27
SELECT *
FROM USER_INFO A INNER JOIN ONLINE_SALE B
ON (A.USER_ID = B.USER_ID)
WHERE DATE_FORMAT(A.JOINED, '%Y') = '2021';