--2025-09-17
WITH TEMP_A AS (
        SELECT  DATE_FORMAT(B.SALES_DATE, '%Y') AS YEAR
           ,COUNT(DISTINCT B.USER_ID) AS USER_COUNT
           ,DATE_FORMAT(B.SALES_DATE, '%m') AS MONTH
        FROM USER_INFO A
            INNER JOIN ONLINE_SALE B
        ON A.USER_ID = B.USER_ID
        WHERE DATE_FORMAT(A.JOINED, '%Y') = '2021'
        GROUP BY DATE_FORMAT(B.SALES_DATE, '%Y'), DATE_FORMAT(B.SALES_DATE, '%m')
), TEMP_B AS (
SELECT COUNT(DISTINCT USER_ID) AS USER_COUNT
FROM USER_INFO
WHERE DATE_FORMAT(JOINED, '%Y') = '2021'
    )
SELECT ROUND(A.USER_COUNT/B.USER_COUNT, 1) AS PUCHASED_RATIO
     ,A.MONTH
FROM TEMP_A A
         INNER JOIN TEMP_B B


--2025-09-12
WITH TEMP_A AS (
    SELECT COUNT(DISTINCT B.USER_ID) AS USER_COUNT
         ,DATE_FORMAT(A.JOINED, '%m') AS MONTH
FROM USER_INFO A
    INNER JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE DATE_FORMAT(A.JOINED, '%Y') = '2021'
    ),
    TEMP_B AS (
SELECT COUNT(DISTINCT USER_ID) AS USER_COUNT
FROM USER_INFO
WHERE DATE_FORMAT(JOINED, '%Y') = '2021'
    )
SELECT ROUND(A.USER_COUNT/B.USER_COUNT, 1) AS PUCHASED_RATIO
     ,A.MONTH
FROM TEMP_A A
         INNER JOIN TEMP_B B

--2025-09-11

SELECT DATE_FORMAT(B.SALES_DATE, '%Y') AS YEAR
FROM USER_INFO A INNER JOIN ONLINE_SALE B
ON (A.USER_ID = B.USER_ID)
WHERE DATE_FORMAT(A.JOINED, '%Y') = '2021'

-- 2025-08-27
SELECT *
FROM USER_INFO A INNER JOIN ONLINE_SALE B
ON (A.USER_ID = B.USER_ID)
WHERE DATE_FORMAT(A.JOINED, '%Y') = '2021';