--2025-02-03
SELECT
        DATE_FORMAT(START_DATE, '%m') AS MONTH
       ,CAR_ID
       ,COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY DATE_FORMAT(START_DATE, '%Y-%m'), CAR_ID
HAVING COUNT(CAR_ID) >= 5
ORDER BY 1, 2 DESC

-- 정답은 아니고 푸는 중인데 내가 어떻게 생각했는지 중간 과정 남기고 싶어서.. ㅎ