--2025-02-09
SELECT CAR_ID, '대여가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

         MINUS

SELECT CAR_ID, '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= 20221016
  AND END_DATE >= 20221016
ORDER BY CAR_ID DESC