--2025-02-014
SELECT CASE WHEN DATE_FORMAT(START_DATE, '%Y%m%d') BETWEEN '20221016'
    AND DATE_FORMAT(END_DATE, '%Y%m%d') BETWEEN '20221016'
                THEN '대여중'
            ELSE '대여가능' END AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

-- syntax error 마구마구 내는 중