--2024-01-09
SELECT USER_ID,	NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B
ON (A.WRITER_ID = B.USER_ID)
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3

-- 한 번에 정답 맞췄을 때 쾌감 진짜 짜릿행.. 넘 조아 !!!!!!!!!