--2025-03-15
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A INNER JOIN FISH_NAME_INFO B
                            ON (A.FISH_TYPE = B.FISH_TYPE)
WHERE (A.FISH_TYPE, LENGTH)
          IN
      (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
       FROM FISH_INFO
       WHERE LENGTH IS NOT NULL
       GROUP BY FISH_TYPE)

-- 서브쿼리 이렇게 쓸 수도 있구나,,