--2024-10-21
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID

--다른 사람이 짠 쿼리 중에 마음에 드는 쿼리
SELECT ANIMAL_ID, NAME FROM ANIMAL_OUTS
EXCEPT
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
